compatibility_flags = [ "nodejs_compat" ]
name = "angular_systems"
main = "./index.mjs"
workers_dev = true
compatibility_date = "2024-06-03"
# account_id = "<(optional) your Cloudflare account id, retrievable from the Cloudflare dashboard>"
# route = "<(optional) mainly useful when you want to setup custom domains>"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs", "!node_modules/**"]},
]

[site]
bucket = "./"
exclude = ["node_modules"]