name: Angular Systems Workflow

on:
  push:
    branches:
      - '*' # deploy on all branches (but a --dry-run flag is added for branches (see code below))

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Deploy Website (gh-pages branch)
      env:
        GH_TOKEN: ${{ secrets.GH_SECRET }} # A token must be created to be able to deploy on the gh-pages branch
        CNAME_OPTION: --cname=angular.systems # omit if your not running it on a custom domain
      run: |
        echo "DRY_RUN_OPTION=$DRY_RUN_OPTION"
        npx angular-cli-ghpages --no-silent --dir="${{env.TARGET_DIR}}" $CNAME_OPTION $DRY_RUN_OPTION
