name: Angular Systems Workflow

on:
  push:
    branches:
      - '*' # deploy on all branches (but a --dry-run flag is added for branches (see code below)) 
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set environment variable based on branch
      run: |
        if [[ $GITHUB_REF == refs/heads/main || $GITHUB_REF == refs/heads/master ]]; then
          echo "Branch is main or master. Setting DRY_RUN_OPTION to empty."
          echo "DRY_RUN_OPTION=" >> $GITHUB_ENV
        else
          echo "Branch is not main or master. Setting DRY_RUN_OPTION to '--dry-run'."
          echo "DRY_RUN_OPTION=--dry-run" >> $GITHUB_ENV
        fi
        git config --global user.name "github actions bot"
        git config --global user.email "username@users.noreply.github.com"
    - run: npm ci
    - run: npm run build
    - name: Deploy Website (gh-pages branch)
      env:
        GH_TOKEN: ${{ secrets.GH_SECRET }} # A token must be created to be able to deploy on the gh-pages branch
        CNAME_OPTION: --cname=angular.systems # omit if your not running it on a custom domain
      run: |
        echo "DRY_RUN_OPTION=$DRY_RUN_OPTION"
        npx angular-cli-ghpages --no-silent --dir="./dist/blog/analog/public" $CNAME_OPTION $DRY_RUN_OPTION
